name: mentalhelth
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
#  carousel_slider: ^4.2.1
#  smooth_page_indicator: ^1.1.0
  getwidget: ^4.0.0
  syncfusion_flutter_charts: ^25.1.35
  grouped_list: ^5.1.2
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  country_picker: ^2.0.24
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  audioplayers: ^5.2.1
#  record: ^5.0.4
#  flutter_pagewise: ^2.0.4
  google_maps_flutter: ^2.5.3
  #assets_audio_player: ^3.1.1
  geocoding: ^2.1.1
#  record_mp3: ^3.0.0
  path_provider: ^2.1.2
#  flutter_image_compress: ^2.1.0
#  image_compression_flutter: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.5
#  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  video_compress: ^3.1.3
  geolocator: ^11.0.0
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.6
  logger: ^1.4.0
  html_unescape: ^2.0.0
  ffmpeg_kit_flutter_min_gpl: ^4.5.1
  win32: ^5.5.4
  lottie: ^2.4.0
  gap: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/gif/
    - assets/images/home/
    - assets/lottie/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansLight.ttf
          weight: 300
        - asset: assets/fonts/OpenSansMedium.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanBlack.ttf
          weight: 900
